# Generated by Django 4.0.5 on 2022-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_advertisement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('to_moderate', 'To Moderate'), ('published', 'Published'), ('canceled', 'Canceled'), ('deleted', 'Deleted')], default=('to_moderate', 'To Moderate'), max_length=100, verbose_name='Status'),
        ),
    ]
