# Generated by Django 4.0.5 on 2022-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('to_moderate', 'To Moderate'), ('published', 'Published'), ('canceled', 'Canceled'), ('deleted', 'Deleted')], default='to_moderate', max_length=100, verbose_name='Status'),
        ),
    ]
